name: Terraform Infrastructure CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      # Variáveis de ambiente para o provedor azurerm
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

      # Variáveis do Terraform
      TF_VAR_db_admin_user: ${{ secrets.DB_ADMIN_USER }}
      TF_VAR_db_admin_password: ${{ secrets.DB_ADMIN_PASSWORD }}
      TF_VAR_my_ip_address: ${{ secrets.MY_IP_ADDRESS }}
      TF_VAR_db_name: ${{ secrets.DB_NAME }}
      TF_VAR_db_server: ${{ secrets.DB_SERVER }}
      TF_VAR_db_port: "1433"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Import Resources
        run: |
          terraform import azurerm_resource_group.rg /subscriptions/${{ env.ARM_SUBSCRIPTION_ID }}/resourceGroups/MyResourceGroup || true
          terraform import azurerm_mssql_server.sql_server /subscriptions/${{ env.ARM_SUBSCRIPTION_ID }}/resourceGroups/MyResourceGroup/providers/Microsoft.Sql/servers/${{ env.TF_VAR_db_name }} || true
          terraform import azurerm_mssql_database.sql_db /subscriptions/${{ env.ARM_SUBSCRIPTION_ID }}/resourceGroups/MyResourceGroup/providers/Microsoft.Sql/servers/${{ env.TF_VAR_db_name }}/databases/${{ env.TF_VAR_db_name }} || true
          terraform import azurerm_mssql_firewall_rule.allow_azure_access /subscriptions/${{ env.ARM_SUBSCRIPTION_ID }}/resourceGroups/MyResourceGroup/providers/Microsoft.Sql/servers/${{ env.TF_VAR_db_name }}/firewallRules/AllowAzureServices || true

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
